import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ChakraUiProvider } from './ChakraUiProvider'
import { Flex } from '@chakra-ui/react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChakraUiProvider>
          <Flex
            justifyContent='center' 
            alignItems='center'
            w="100vw"
            h="100vh"
            background="#f6f6f6f6"
          >
            {children}
          </Flex>
        </ChakraUiProvider>
      </body>
    </html>
  )
}
